services:
  nutrifacts_api_ai:
    container_name: nutrifacts_api_ai
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - app-ai-network
      - nutri-shared-network

networks:
  app-ai-network:
    driver: bridge
  nutri-shared-network:
    external: true